language: java

sudo: false

env:
  global:
    - secure: 'GfoA8QZ2NaN61FEePvUWzM+Rq8TV5Rk3hcUBYDmjXPU5IqO/ytx5DMtpiS0fIZSrq9+efrCqPOP5cAlMxrvM+Q/I9fknUTsetjV9jEbgoAVV9F/97h5VnWk67dfHPz7bVUvbF+mrnczrPCJUDd2/T7E1LuVBHZHJ3FHTk3W+TaE='
    - MAVEN_SETTINGS='.travis/settings.xml'
    - MAVEN_OPTIONS="-V -B -s $MAVEN_SETTINGS"

branches:
  only:
    - master

jdk:
  - oraclejdk8

install: ./build ci-prepare $MAVEN_OPTIONS

script: ./build ci-build $MAVEN_OPTIONS
